CREATE TABLE [dbo].[Checking_EventLog](
	[Id] [int] IDENTITY(1,1) PRIMARY KEY,
	[EventValue] [xml] NOT NULL,
	[ChangedBy] [nvarchar](255) NOT NULL
) 
GO

CREATE TRIGGER [TRG_EventLog] ON DATABASE
FOR 
	/* SELECT * FROM sys.trigger_event_types */
	CREATE_TABLE	,
	ALTER_TABLE		,
	DROP_TABLE		,
	CREATE_INDEX	,
	ALTER_INDEX		,
	DROP_INDEX		,
	CREATE_SYNONYM	,
	DROP_SYNONYM	,
	CREATE_VIEW		,
	ALTER_VIEW		,
	DROP_VIEW		,
	CREATE_PROCEDURE,
	ALTER_PROCEDURE	,
	DROP_PROCEDURE	,
	CREATE_FUNCTION	,
	ALTER_FUNCTION	,
	DROP_FUNCTION	,
	CREATE_TRIGGER	,
	ALTER_TRIGGER	,
	DROP_TRIGGER	
AS 
	BEGIN SET NOCOUNT ON;
	INSERT INTO dbo.EventLog (
		EventValue,
		ChangedBy
	)
	VALUES (
		EVENTDATA(),
		USER
	);
END;

